## 异步函数必须要catch
在 Node.js 中，如果一个未捕获的错误（uncaught error）在顶层代码（即没有被任何 `try...catch` 或者 Promise 的 `.catch()` 方法捕获）发生，它会导致 Node.js 进程崩溃。这种情况下，Node.js 会打印错误信息并终止进程。

```javascript
async function asyncFunction() {
	throw new Error('This is an uncaught error');
}

try { 
	asyncFunction(); 
} catch (error) { 
	console.error('Caught an error:', error); 
}
```

在这个例子中，尽管 `asyncFunction()` 可能会抛出一个错误，但由于 `asyncFunction()` 是一个异步函数，它会立即返回一个 Promise，而不会等待异步操作完成。因此，在 `try...catch` 块中捕获错误的尝试会失败，因为在执行 `try` 块时，`asyncFunction()` 还没有执行完成，因此错误不会被捕获。

## 使用`escape`转义特殊字符（也可以不用）
（Vue 的 `{{}}` 插值表达式和 `v-bind` 指令都会自动转义特殊字符）  
对用户可以自定义的信息，转义特殊字符  
安装： pnpm add lodash
```js
import { escape } from 'lodash';

let result = escape('<html>');
console.log(result);  // 输出：<html>
```

